
version: '3'
services:

  svc-userauth:
    build: ../users
    image: 098106984154.dkr.ecr.us-west-2.amazonaws.com/svc-userauth
    container_name: svc-userauth
    networks:
      - net-notes-users
      - net-db-users
    # DO NOT EXPOSE THIS PORT ON PRODUCTION
    #ports:
    #    - "5858:5858"
    restart: always

  svc-notes:
    build: ../notes
    container_name: svc-notes
    image: 098106984154.dkr.ecr.us-west-2.amazonaws.com/svc-notes
    depends_on:
      - svc-userauth
    networks:
      - net-public
      - net-db-notes
    ports:
      - "80:3000"
    restart: always
    environment:
        REDIS_ENDPOINT: "redis"

  redis:
    image: "redis:5.0"
    networks:
        - net-db-notes
    container_name: redis

networks:
    net-public:
    net-db-notes:
    net-notes-users:
    net-db-users:
